services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud_app
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloud_network
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_HOST: mariadb
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

  mariadb:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: nextcloud_db_mariadb
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_nextcloud_data:/var/lib/mysql
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  nextcloud_network:

volumes:
  nextcloud_data:
  mariadb_nextcloud_data:
